import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { FormEventHandler, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [name, setName] = useState("");
  const [email, setEmail] = useState(undefined as unknown as string);
  const [id, setId] = useState(0);

  const handleSubmit: FormEventHandler<HTMLFormElement> = (e) => {
    e.preventDefault();

    const request = {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name, email }),
    };
    fetch("/api/create-user", request)
      .then((res) => res.json())
      .then((res) => {
        if (res.error) {
          alert(res.error);
        } else {
          setId(res.id);
        }
      });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {id ? (
          <div>Hello user {id}</div>
        ) : (
          <>
            <div>You do not have an id, please enter your information:</div>
            <br />
            <form className={styles.form} onSubmit={handleSubmit}>
              <div>
                <label>Name: </label>
                <input
                  type={"text"}
                  id={"name"}
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                />
              </div>
              <div>
                <label>Email: </label>
                <input
                  type={"text"}
                  id={"email"}
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                />
              </div>
              <input type={"submit"} value={"Submit"} />
            </form>
          </>
        )}
      </main>
    </>
  );
}
